[package]
name = "vmprotect"
version = "0.1.0"
authors = ["Лач <iam@lach.pw>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
real_c_string = "0.1.1"
widestring = "0.4.0"