[package]
name = "vmprotect"
version = "0.1.2"
authors = ["Лач <iam@lach.pw>"]
edition = "2018"
description = "Unofficial VMProtect SDK for Rust"
license = "MIT"

[dependencies]
real_c_string = "0.1.1"
widestring = "0.4.0"